// flow-typed signature: fd942663e05a62f35ecc70424e2418f3
// flow-typed version: <<STUB>>/redux-saga-test-engine_v^2.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-test-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-test-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-test-engine/build/core' {
  declare module.exports: any;
}

declare module 'redux-saga-test-engine/build/index' {
  declare module.exports: any;
}

declare module 'redux-saga-test-engine/sagas/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-test-engine/build/core.js' {
  declare module.exports: $Exports<'redux-saga-test-engine/build/core'>;
}
declare module 'redux-saga-test-engine/build/index.js' {
  declare module.exports: $Exports<'redux-saga-test-engine/build/index'>;
}
declare module 'redux-saga-test-engine/sagas/index.js' {
  declare module.exports: $Exports<'redux-saga-test-engine/sagas/index'>;
}
